SELECT (CASE WHEN GRADES.GRADE < 8 THEN 'NULL'  ELSE STUDENTS.NAME END), GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS, GRADES
WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, NAME ASC;
