/*SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID;*/
SELECT ANIMAL_ID,NAME
FROM ANIMAL_OUTS
WHERE NOT EXISTS (SELECT NULL FROM ANIMAL_INS WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID)
ORDER BY ANIMAL_ID;