SELECT A.ANIMAL_ID, A.NAME, A.DATETIME AS in_time, B.DATETIME AS out_time
FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME ASC;
